name: spark-iot
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pip>=23.0
  
  # Core Data Science
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  
  # Visualization
  - matplotlib>=3.7
  - seaborn>=0.12
  - plotly>=5.14
  
  # Jupyter
  - jupyter
  - notebook
  - ipykernel
  
  # PyTorch (M2 Optimized)
  - pytorch::pytorch>=2.0
  - pytorch::torchvision
  - pytorch::torchaudio
  
  # TensorFlow (use pip for M2 compatibility)
  
  # Development Tools
  - pytest
  - black
  - flake8
  - pylint
  
  # Pip packages
  - pip:
      # Spark
      - pyspark==3.5.0
      
      # Streaming
      - kafka-python>=2.0.2
      - paho-mqtt>=1.6.1
      
      # AWS
      - boto3>=1.28
      - awscli>=1.29
      
      # TensorFlow (M2 compatible)
      - tensorflow-macos>=2.13.0
      - tensorflow-metal>=1.0.0
      
      # Deep Learning
      - torch>=2.0.0
      - tensorboard>=2.13
      
      # Web Frameworks
      - flask>=2.3
      - streamlit>=1.25
      - fastapi>=0.100
      - uvicorn>=0.23
      
      # Data Processing
      - pyarrow>=12.0
      - fastparquet>=2023.0
      
      # Cloud SDKs
      - google-cloud-dataproc>=5.4
      - azure-mgmt-synapse>=2.0
      
      # Reinforcement Learning
      - gym>=0.26
      - stable-baselines3>=2.0
      
      # Utilities
      - pyyaml>=6.0
      - python-dotenv>=1.0
      - requests>=2.31
      - tqdm>=4.65
